# https://taskfile.dev

version: "3"

vars:
  JEKYLL: bundle exec jekyll
  WHOAMI: whoami

tasks:
  dependencies:
    cmds:
      - nix-shell
      - gem install bundle && bundle install && bundle && bundle exec jekyll serve --incremental
  default:
    cmds:
      # - git pull
      - task $(cat ./Taskfile.yml | yq '.tasks|keys|.[]' | fzf)
    silent: true
  serve:
    cmds:
      - '{{.JEKYLL}} serve'
    silent: true
  draft:
    cmds:
      - '{{.JEKYLL}} draft "My new draft"'
    silent: true
  post:
    cmds:
      - '{{.JEKYLL}} post "My new post" --timestamp-format "%Y-%m-%d %H:%M:%S %z"'
    silent: true
  git-add-commit-push:
    cmds:
      - git add .
        && git commit -m "update"
        && git push
        && git status
        && echo "git push success"
        || echo "git push failed"
  mdimg:
    cmds:
      - echo -n '![{{.CLI_ARGS}}]('$(task awkimg -- {{.CLI_ARGS}})')'
    silent: true
  awkimg:
    vars:
      TGPT:
        sh: which tgpt
    cmds:
      - curl --no-progress-meter -F"file=@$('{{.TGPT}}' --img --height 630 --width 1200 "{{.CLI_ARGS}}" | awk '{match($0, /Saved image as ([^ ]+\.jpg)/, arr);  if (arr[1] != "") {print arr[1]} }')" https://envs.sh
    silent: true
  exit:
    cmds:
      - exit
  post:
    desc: Usage is the cli argument way `task post "<title of the post>"`
    vars:
      DATE:
        sh: date "+%Y-%m-%d"
    cmds:
      - cp ./_posts/2025-07-04-static-site-generation-is-frustrating.md ./_posts/{{.DATE}}-{{.CLI_ARGS}}.md
