# https://taskfile.dev

version: "3"

vars:
  JEKYLL: bundle exec jekyll

tasks:
  dependencies:
    cmds:
      - nix-shell
      - gem install bundle && bundle install && bundle && bundle exec jekyll serve --incremental
  default:
    cmds:
      # - git pull
      # - task $(gum choose "server" "draft" "post" "git-add-commit-push" "exit")
      - task $(cat ./Taskfile.yml | yq '.tasks|keys|.[]' | gum choose)
    silent: true
  server:
    cmds:
      - bundle exec jekyll serve
    silent: true
  draft:
    cmds:
      - bundle exec jekyll draft "My new draft"
    silent: true
  post:
    cmds:
      - bundle exec jekyll post "My new post" --timestamp-format "%Y-%m-%d %H:%M:%S %z"
    silent: true
  git-add-commit-push:
    cmds:
      - git add .
        && git commit -m "update"
        && git push
        && git status
        && echo "git push success"
        || echo "git push failed"
  mdimg:
    cmds:
      - echo -n '![{{.CLI_ARGS}}]('$(task awkimg -- {{.CLI_ARGS}})')'
    silent: true
  awkimg:
    cmds:
      - curl --no-progress-meter -F"file=@$(tgpt --img --height 630 --width 1200 "{{.CLI_ARGS}}"| awk '{match($0, /Saved image as ([^ ]+\.jpg)/, arr);  if (arr[1] != "") {print arr[1]} }')" https://envs.sh
    silent: true
